# Generated by Django 6.0.7 on 2026-07-17 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Barcode (for API)')),
                ('calories', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Calories (per 100g)')),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Protein (per 100g)')),
                ('fat', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Fat (per 100g)')),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Carb (per 100g)')),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of meal')),
                ('weight_grams', models.PositiveIntegerField(verbose_name='Portion weight (in grams)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories_limit', models.PositiveIntegerField(default=2000, verbose_name='Calorie limit')),
                ('daily_protein_limit', models.PositiveIntegerField(default=150, verbose_name='Protein limit (g)')),
                ('daily_fat_limit', models.PositiveIntegerField(default=70, verbose_name='Fat limit (g)')),
                ('daily_carbs_limit', models.PositiveIntegerField(default=200, verbose_name='Carb limit (g)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
