# Generated by Django 6.0.7 on 2026-07-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Calories (per 100g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Carb (per 100g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Fat (per 100g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Protein (per 100g)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_calories_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Calorie limit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_carbs_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Carb limit (g)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_fat_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Fat limit (g)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_protein_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Protein limit (g)'),
        ),
    ]
