# Generated by Django 6.0.7 on 2026-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_food_calories_alter_food_carbs_alter_food_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='weight_grams',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Portion weight (in grams)'),
        ),
    ]
