# Generated by Django 6.0.7 on 2026-07-23 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_meal_mealitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='food',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns the record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product name'),
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together={('owner', 'name')},
        ),
    ]
