# Generated by Django 6.0.7 on 2026-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_food_owner_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='portions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Portions'),
        ),
    ]
