# Generated by Django 6.0.7 on 2026-07-29 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_food_portions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealitem',
            name='meal',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Morning Snack', 'Morning Snack'), ('Lunch', 'Lunch'), ('Afternoon Snack', 'Afternoon Snack'), ('Dinner', 'Dinner'), ('Second Dinner', 'Second Dinner')], default=1, max_length=50, verbose_name='Meal Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
